(tests
 (names test test_ee2_fc test_work_set test_staleness)
 (libraries
  abb
  abbs
  containers
  oth
  oth_abb
  sln
  terrat_base_repo_config_v1
  terrat_change
  terrat_change_match3
  terrat_data
  terrat_dirspace
  terrat_job_context
  terrat_tag_query
  terrat_vcs_event_evaluator2
  terrat_vcs_provider2
  terrat_work_manifest3))
