(library
 (name sgs_service_orchestration)
 (wrapped false)
 (libraries
  abb
  abb_curl
  abbs
  brtl
  brtl_ep
  cohttp
  containers
  githubc2
  githubc2_abb
  jwt
  logs
  openapi
  pgsql_io
  pgsql_pool
  sgs_api
  sgs_config
  sgs_eplib
  sgs_redirect
  sgs_service
  sgs_storage
  sgs_tenant
  sgs_user
  unix
  uri
  uuidm
  yojson)
 (preprocessor_deps
  (glob_files_rec sql/*))
 (preprocess
  (pps ppx_blob ppx_deriving.show ppx_deriving_yojson)))
